---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gluetun-nordvpn
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  namespace: media
spec:
  encryptedData:
    WIREGUARD_PRIVATE_KEY: AgB+3YQo99jIMU9gcf4CP1nT+utit2G5sEbjHYO0parobagtFNlaO//3ViQyepXiup1IszCYNicDrVcU9Y1FdY1nvKMAqrF0Qwj0WtHsDKLvQ0YmMzbNCCniAkMRLpHOwg92KUeXnPTCsgJ2bYUiM0DB6Q+2pU6/jEhCmiwjQ3kpeRzIK8tUSvCrMKnjBmWMjkG3c2GM2gyVCin8/OaSkgo4TTrLZomZx2gpJjtjHti0BC7CplTLQQh7rq3N0/wuSdp5nnKsa6NabPS/4DCAcKzo/vJoigMY6mHnmf45QPqqSzB+J7Z/VQhzWWQKOKry93H6AEqIZKlYoW3/I+2+wbhXwBTrF0KjJM2AbsJx2JH+lXLeTVNsi2Dyz+AUz6pjiNll/zzijFNJCD73pLIFfKIHITnhI55SuvyG34k0H9dmSCT3YBeQLoqOrQNLkQ+RzDqjDYLlkvCuqiTKxCEx1vQspOm0QiwUDVM7JrAGnf4benigd9Z+V+XREzcktIK40ArQHEoJJ0LB5sXVTurPJ4L36/C0+GS7b+18vk1ao6CCVrEx8QJBWsJfjTJbNKZNi8pphVejABo1+0ZobsCkB7g8KLsjCwd3STWq0Y2R9g6XCxb1WPrlFZdE0uOJekWLd46FElAxJMhw2+ICqQpDJuv8rFngNFObL+K4g/HYMGJ/rwguBAFGx4BRl09oT6coG9wJU3++Jm53UegVEB0VlXUSkBHVH2C4GSYLtptIRJSg1o7azm+bTnFtsmmOaA==
  template:
    metadata:
      creationTimestamp: null
      name: gluetun-nordvpn
      namespace: media
