---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale-auth
  namespace: networking
spec:
  encryptedData:
    authkey: AgALIZSTm5yf5MujvhMpcsmVgymL+mNlHNRZYNk/0fewjtok/aUGVfq5zp6LwYkU4IFDZavovU7hgDvKjmk2JWdLj4X8TwxaHSTM1P4JdpX7++jjUZxfKuSW2P+bzsxnBiInfDyMpmKFIJkbb1GzD7tUZzuQdjG3rXfGXLELhwzGfjilxdzaoEBlreUrIBdaoKx3U8cq7/mFa6Uy7aLEiMKguSHw9QWU5LEUadOpAHil6q85BcNqVSKFw4WzYASCq+fiGcVgt2jFxcjypfhWq34CcfotEYnc+wLB2cAAkiMkaR6AFKc0MLoRan/XDfUubGPjFlBr9cEGHx0FpsZcFzFD8rHidSUoWclfuwqCdO486Y35orZmDnCG0cQbUtujK1bHoldEaUlNjsEKrhfuxPe6/Om23BCmgIV/n2NX7NTfSXFJPjzF7vuz47ftyzPETkAnAdbMxIMPmI/WrEZxiUUyJ5D8tIxxJWz4EBfaSI9Q9KU51oSibuBKe/qWM33Q+lLbAvAbwYCz8dVx5tHKmYwQOUUNXk0W4BJTkC44XvLtMMiOZMsyQHE5/UNRl3ln9Y2du+OEwVF3lNNgQjPmNTQJwNtcYDjqbzdMPN5hp8U2QIK/BrF9i8iH4CKJSZBiJ90AAFG3g31iH2XqTmlbRr9tiCHjTVC6G8k3cUiULdKjcyGfv/GpNwwMXkxT8jT2m5GitB6ilX2gax0T6qbx6ofRnxh2hLnzhhnv36KzkPzH+aulZlrbP/2mcf7Yuod7ne2th8hVRj0gO7dAmT4eVw==
  template:
    metadata:
      creationTimestamp: null
      name: tailscale-auth
      namespace: networking
