apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: externaldns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.14.5
    helm:
      values: |
        provider:
          name: cloudflare

        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudflare-api-token
                key: api-token

        policy: sync

        sources:
          - ingress
          - service

        domainFilters:
          - isaacwallace.dev

        txtOwnerId: homelab-k3s

        triggerLoopOnEvent: true

        serviceAccount:
          create: true

  destination:
    server: https://kubernetes.default.svc
    namespace: networking

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true