name: envoy-gateway
namespace: envoy-gateway-system
syncWave: "-2"
repoURL: oci://ghcr.io/envoyproxy
chart: gateway-helm
targetRevision: v1.3.2
values: |
  config:
    envoyGateway:
      provider:
        type: Kubernetes
