---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: adguard-auth
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  namespace: networking
spec:
  encryptedData:
    ADGUARD_PASS: AgCaAQwXYqxaGo/VJsGydUt1wxaB+cAh8YP1ccaoz0EQpkAJPHM0LdOXfsT/Y3hsZyfeP+VkCWYCWVAmAcRQgTUpsUhzhcjR7bkx5hqedeeq/AK9Utgsp0mbLa5Gt7fF9FNoAiB0S3htjY98bbXu09B233bk+K5R6qD/ZmGPkSK9CxTj+GgPskUXezbr/OXDTgT6beUdhqTd7pQtll0DBTPsZfWsfxF+5PFrXGbjouJDRMeo1Q/rceaPJZmVjy6VRPbzWxJRHl06xT8bmfEPdcDuSfGM8lQ6y8gGxhszJ73mMD9YqAJaVGrBFd6IQvlLu2/hTTXNsoGA/d0AFlP5W5ByRweY4w83xGHonD0GsLDp7k7euzw+EtdMsI7fZT8NpGVodsRaOB82xWHCfmThOgXqXpi8yJh105j8k3yXjcrwYgWGArk6jBh8+Ck9f5r6d4tYb29o3R9BIv7hvJe7URVsZlST9pwWQ8UodLACjMiKahm5zwpiJ+8p9Z6KaP+vQnLPu1km5/brLUBYkEfpyZOmcuwjepTUlgBu1gAWiEujzRw9d9i8ljW8ncJ+DzRIgIA1KE0a/r7hBgNdnaoF0lGoGHdKVyLrW7/HufDzHmlsZArFeqGgoeKCtl4JFuSHax0x1Rb2C3GhSQDYd9gWQqZ8RLI/Kdb8FkIBk8ADyz9VfMdtXdyfAn61EaRWGEnx9ApK9Kk7C0/QnN/i+0xr
    ADGUARD_USER: AgBUNvvXAKt1ZfFipicr9RnP3ENiULrDGAW6jLn5VPcF+eZTq684HerKVw2BWdJxkk0ik1vj/GPudRJK3jZP37eh/xWX33io8kspUexxezbRGBm9t1WKipzbF4x33faqbgKEcEiFuXtO90+hFarOCsx74ntvr+VyDEpRKeLBvIKrzd5tG8X8V9YvcqbSrDwLQQ2ldLnX2wzxc1lSvQ3WQRaXzweA3jt5uuuqcdqyKx8/mlZt8O9HqPP/Le4+TFVm2iqFftQHvGm10u6yWfVptjBLIEyvYlUSyXiM4edr6DvjKY6NfR4iIeJRh+yclFpcuqBEbMsTqeSUP+gjgyRt1N5cIlUC7aK0SMxGEHTtoJvWcq8Qck9lFXOUR2rPio15dgFRZ1ajuFcRgh0ZHBXduOItZkH2TExE2psYsOg6LTtA4MV9fifto6xCqBRtKWYeTVGoDUhRbhlju+vGu3Xt/WLU6czN3fino2qM+pK2cV5IQDGmKXIOfzYS42H34H2rmnbSHrghSyPAShynY0evrL4kZ1WdGB84XOQFdsYIXaRdbd8FaWizaKmjpKEBVnvAqyhXWKABZL6Mf891WrBy0WzcHl/q97OVHvd035xWLMHvqkAE8lYePY4ksIXc4Otk9f4X+BmLJkQesJRkDGZPHOTZCWP3wahb6m/j6I4pYO+xGGaT5ArBKy3M3n0lBYHIu3TBAM9Rag==
  template:
    metadata:
      creationTimestamp: null
      name: adguard-auth
      namespace: networking
