apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgDdrNiyYHnOSnNTvuhKoQZG5TQ/YzbiiwrKWIy4zxHF+gL2ziwt5djLInhWMNv+GJNUv2oeu0ixF95Mu4qBDFkRGUksd/8QOTWlfAV7LkSuqZrMJ/SRkG33GuD5TWGBHXLlhxFH9DAv/Uw4+VBf6zC3BN1b2Ecg+k0yd6fNA1K1V/Tga42hj2rP0tPghkLPNqebTr+D242APWojH/u7GB1u9/CgoGfDz0jvYVp0AsgJETMv/2KZJ/hwGKB8l8RJvlm7uFuna0y6YDwUru3KKFkvPbadM5iFP0NBC5hlFbgw6gimdnfiL+xc+Ex/5+m5KLhe83MCAXdE0hTVtrQYvPLDRGzdNvkrq2yKaHcicP3tRHebyBjv6tgbyqqEYtaye3oOelCmiGTFGI7CorIuJrwEU7iGdBBLNeDlbWTzzdcCbPDzkmSwC83L7FSAgXPGWlH1tteU3S3uJsADQ6dnmKzz2MGvfJ4zyVtAQulwzclpFcuKAnYMOFK3bIwKSXFlP138wwBIkIzdH2VKHCeJIWmgr15JmZTl9JMlTOJUGOlzFgYm4S8GpIkZ5m7ip21aF9EBBqdagohFe1+Z1KZ/E5EPS4qCRDMWutWCFeV9WBi3RrttL/pYIYSG4Ia/e8mZcCm0yZe9zFb+8usT2yJ6Uz5u9Al5s2rTK1JOOoCHIwZ6QDQsIZPfjjEPWPhFxWMRwH11Qal+o9AMURPeHJlq
  template:
    metadata:
      name: grafana-secrets
      namespace: monitoring
