---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: portfolio-minio-secret
  namespace: portfolio
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgAGAJp0dToyX+Psfh7zbJyulAhw7cc4S3ncbuftO84KnlS7RCWpItymZMhFT3788rBIJovuNG/lGC0COe83nAzz6a9CVbcK0JEUj+PFgtWEKH+Ed9giQJFlZDGdYMlJEPKlsudmiiJrNG49rGPY+rAdqLALVAjaHLaETiaP/+MKbW6h/pc3VuTYqAmxQtAAiQqdOp8Eu2y/oddT1l2rNVuSqmxjaSVsMcvKFEJ2NDl1L/6m34568clTDA7oHoGnGxUqTTPas1oPbBJHurZZCcdm4eL09qBr2zZzvuPVqN247Uwz5e/L19hz4vmaa2HRAuHnJRAofY3IkT/IjTKKvSmpZNj7fn3Kfo4FX7ePIsP8bNoYnhLvjQEOTQTV+/fMkYVVXhsP+puPILvtpz2Hzx874XK2jd8CCOqW4T6rueerkFrUwukxZyXXP+IIwxLqC/EBjFi/vc4ZFBmXkK5fVehrIEeZUaS8U8din4pkftlkua/r4RaKtBum2O5gJKi9DcNSmVTB356NfyFuCGyTfb6z6MGidnQ97kBJqrMvFM6eh6SuYUwKYsgVhbzdPeYCPG7ciNe2GbFJTfyFDD6l/t4E7eOZNntH//JYTQF9IK2+mS0mgL/Vu5FEP2/erZ8N5GPxzt6E5YYqz9KW2i2hIqM/6BRWouLRxUxHj0CnJJU+l04R7v5stW04aDsfAXa0ci9oXLNXR5gb7u3o
    MINIO_SECRET_KEY: AgCQzgVIclZ+DNOrF3KsZgJADf5qfVWGlOY1HefK0dpBpu4MHAzKVSZUXjo+QW1Khm1EuBJTvhwQ+Jwf1m/aH32Zj16wLXK5yHc8XwzYECRvbFyPZ5PIHcmf18YgoGxjb8fwqAvznpUbaKTKj+90U2CURt0K18S189/n1x+VD4RuVocXcufCZcGyFoTXg2IxiQ8FwTocxj02ipppwrOwYYEV8BkMHZMlS/UFZZjH6yq/Nyc62x19iDb4+3lvxDdC3YrTooGNRNqgWcDeg5D/70l3K5ZKKo4EAbFUoDg+YTuP5mTyRgHTCkDu+P/bqOdSCJF/t+L3nCkJaypgDA8MdfCE8etNdmp94QFdG9xfFUYSwhrIIpHxUvB+o1wR6n0WFr3hNMFc6ijGFSVANCO4qDCSm9TEyzpHnRLEDmOr3RKzPlyLeblqTvyB7h/urHm/a8ETImuuMiNGcSt//YrPXb6ylDBtLDh0S3791JjqdiGfNfeEUZHazsVIcVQ4D1VFRLAO4SQdVIKWMppp3S/cn5B9eM2ioj/WBN1T5vsYWCJiKL7vD6Znarh2vUfL1xSbv819Yhopn+gXAL4lf3rXeIuxJ8aL1Mt2/a+96mR4ZAn/A3kpkmejQI0vZ2LN5oTE8ksCMhdJz3/jW6OwfxfmWEJOPZFH9nFgF3dlXYhRM17CcpbHlDWXoLF8PQwGp5oSioSRbH8W0Ih5wovxGZGC
  template:
    metadata:
      creationTimestamp: null
      name: portfolio-minio-secret
      namespace: portfolio
