name: sealed-secrets
namespace: secrets
syncWave: "-5"
repoURL: https://bitnami-labs.github.io/sealed-secrets
chart: sealed-secrets
targetRevision: "*"
values: |
  fullnameOverride: sealed-secrets-controller
