apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: deluge-vpn-creds
  namespace: media
spec:
  encryptedData:
    VPN_PASS: AgCKwsc/DwQOCxhBj3/T84clBa3R6FGTFLTvplygE0knAuXsY6iFDZGenTQbxiB2JzjWBmvs7f2PUKFjOaG5p31/XQL11zw/6RJd6deVSjaJd1eLKRLhlEvvDLsjj42kY16kjWqFV6E4flDj1Wt4wMAG1m4G+bVi1thnca0ktPfOPJMwPVrk+XY5L6PyKitDiSl4G5nwjF+CN/4HqoM/VzKyhU5iCquqn+T7SiQs0/GsOlia7f25XN4sqSgnyQY4Xxk8CTOOfu4WYAYz2zO8SLyl1lZGgSWzFarjrtYi1V8y30ngZqgiXEKJY66lMIbG3t5KBU95KdOZxNjDM2HUhbN7iZnm1uNX0YOnTYVeQebTFYcC0LM2ZVvyFT+X7EXwwIqwI8i9GVwmR4U6aAuU9/5yr3ZTEVhXSu9r12qRcK6nc8K3K8GEJRUDUyZh+Q5yldg1xnLSQk8UezN5crMF8wzC1hYApuJw4zB24tc/ZS5j73m5OlAJBUw46J1l4/kqFy35jZpp1Q+bOIiu5oyRd8U48IIOlN6GsrhSXI42QQoETfxMokfXZK8uBhZoNU81YQeJIJr0KKJshG5AJcFA3U+WxKIE241jW3Tziw7uVFDzct8TzHXLQ7BN3NYHArggF/X1nMVYdO4ad4/ah6Bk21dkkPk/iqSFXyFGUVwUzpl/6rN7CcCjq2QUEPuzm7xKNAJO8+tMwka/WweEFfA0
    VPN_USER: AgAqkQ8/y4PzqLJ0RvwXG4+72/5fmsH4FJOCDHis1x+u/HHGbvXKL+Yuo8q570hJ0bIJH1aA5E9zbHctxBijwOx64JR+g2++gIo5CK5LSPqP1j6veI3YuIsRy2Pn8uV3K5rDPd7bNJgwv7/Cy2+9cOqyZo+aHoTjuazzSV0mHBIstpQYU+rB33La6uRsRrpKUz83c/gztzgYqd3Bcyn0JwpacdRBClVqBZXVGaNXahKae9Wyh+iV3dh4loidZ8i8HcnLdKZK3s6rUntAwNqsTYOQ6tlDtQQ48Re58wtxmmlWCKodcZiTrcTf1Be6uG5aecBpArxW1TueCvfEDChYPk9GCX8XzcO4eUxOXU0xB6yGYySVjqq6yhmavOCt10825doKiWati4tidzbnOQac+epZIKAYxrGwJXRZffJFiuVSktaB9qXh6Cb2t/nfWJ2lFXNC8Q+DaARzz2YUY/90L2RCF88gCKH8Dmw30DcaLSVHF6naZyFIVDj25t4Qdv+YZB7wVHDK23lUcoehvl4ytzxvuGvB1Yxah7qGLB1KOQ6IKZydC0OgZwFa1WzEQEeVR5LJCWig5NdJgkRI365zA/azY8msb1AyIGuCO58uEdMnlg4aOBfmOrLsx9pi6rSL5k06aV4g5oI1Wo3qpMOt98EtIIvK14Y6LjddNzzri/3EiZ7yjvuFJUEN7qniGbR8BJ3OVdb21A==
  template:
    metadata:
      name: deluge-vpn-creds
      namespace: media
