# =============================================================================
# Terraform describes the machines. Ansible configures them. The handoff between the two
# is this generated inventory — so node topology is declared exactly once, in var.nodes,
# and Ansible can never disagree with what actually exists.
# =============================================================================

locals {
  servers = { for k, v in var.nodes : k => v if v.role == "server" }
  agents  = { for k, v in var.nodes : k => v if v.role == "agent" }

  # The lowest control-plane IP is the cluster-init node — the one that bootstraps etcd and
  # that every other server joins. Sorting keeps the choice stable across runs.
  primary_server_ip = sort([for v in local.servers : v.ip])[0]

  host_vars = {
    for k, v in var.nodes : k => merge(
      {
        ansible_host = v.ip
        node_pool    = v.pool
        node_zone    = v.host
      },
      length(v.labels) > 0 ? { node_labels = v.labels } : {},
      length(v.taints) > 0 ? { node_taints = v.taints } : {},
      length(v.kubelet_args) > 0 ? { node_kubelet_args = v.kubelet_args } : {},
    )
  }

  inventory = {
    k3s_cluster = {
      children = {
        server = { hosts = { for k, v in local.servers : k => local.host_vars[k] } }
        agent  = { hosts = { for k, v in local.agents : k => local.host_vars[k] } }
      }
      vars = {
        ansible_user      = var.ci_user
        ansible_port      = 22
        api_endpoint      = local.primary_server_ip
        primary_server_ip = local.primary_server_ip
      }
    }
  }
}

resource "local_file" "inventory" {
  content         = <<-EOT
    # GENERATED BY TERRAFORM — do not edit.
    # Source of truth is provisioning/terraform/terraform.tfvars (var.nodes).
    # Regenerate with: terraform -chdir=provisioning/terraform apply
    ${yamlencode(local.inventory)}
  EOT
  filename        = "${path.module}/../ansible/inventory.generated.yml"
  file_permission = "0644"
}

output "cluster_summary" {
  description = "Node placement at a glance."
  value = join("\n", concat(
    ["", "  NODE              ZONE       ROLE     POOL      vCPU    RAM  IP"],
    ["  ----------------  ---------  -------  --------  -----  -----  --------------"],
    [for k in sort(keys(var.nodes)) : format(
      "  %-16s  %-9s  %-7s  %-8s  %5d  %3dGB  %s",
      k,
      var.nodes[k].host,
      var.nodes[k].role,
      var.nodes[k].pool,
      var.nodes[k].cores,
      var.nodes[k].memory / 1024,
      var.nodes[k].ip,
    )],
    ["", format("  %d control planes, %d workers across %d Proxmox hosts.",
      length(local.servers),
      length(local.agents),
      length(distinct([for v in var.nodes : v.host])),
    )],
  ))
}

output "primary_server_ip" {
  description = "The cluster-init control plane; the k3s API endpoint every other node joins."
  value       = local.primary_server_ip
}
