---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: garage-auth
  namespace: cloud
spec:
  encryptedData:
    admin-token: AgBc+0xhZ5l7BOaJgXVSULtyVBmsfGDAERtAp9/YDojGMpWhSkZHTICiySXznNAKtEtl0r+QlRJM2WWtLl0XeIWFGNOLo2i8IENlExcoS+6J/LTGVS1oeum6kOO/DRNOH1ax7dKsfdeHcdXRS2CBzCrTbp8lQyOJOIIDZ2V6pccHdUZn5NKZTMM+/qF56NdIvJ/zvt1qm1jMCA2pURx6NtaIVL7Ot9qWh7FjxHvSIEUPpXe6en5JVai42IH6GGPPAPg2ewb4tYczxZ7s8jsf9kV4nMQoxePukgKE/Um+gXhDRuimLmp4dkRM8zCO1nlDGIdtqVMSnhqIgCgKK4vOd+swm79J/h+VJsTu56rIs/j2i/3Pj9IQ38czKy2aFvVPEVaCHhAJE3ICUbtzW66yYTgDwxZWJvT+BEEKbhToiq4nQtPbkQDdjdECde97U//96iceWqPkWUcoGI3AH7VfU/UmRkWc+2Q8g8IwlqCwW0mTkFhUrdeVPLDtkbs6RBV75gadOSjZQiyYpEVNtSmEL5T6hEJVvwcqofHK2PctisZbsYjTRnFo8SGTmE02XuGdS99YyfbSAi6dVD2UGe2r+dnhHzP4/IJRzXxgbih3Uj9AW6zuordp0SLgkhlpW7mtnxXmz2qWDSl+w0dEjn7xarC4yfgsCFu7clA460oUwFNx8foFgY7XBgDD8H/wbBRDjpclNuTEeGi1Zs/BDqFUdEF52qghNdQKMvS49cu2OqzZhJXHRBs0F/GJhKiRBA==
    rpc-secret: AgAUORnQfesBtX5Yz/2f0ns1F6x6FihuRwpgrI3iHcTgTUO9UHtMrQfE2nIGueOKGnjbGkfAAb3oPXWsZFgDnns6S75YIeD77bOMkkyJPXDCIcbU0aWeCoNQXJcuPujG+Eev1LP7FFv/ixtPAIvifHpvKnSpf3wqf6hjXuZ+3G1/z4/MRu4aZSyOUtVqrNE+CjhubtVodJc2fVgvE0TjhSx50/uv13yoRQg/f3TF+ks/MxBmT6kqbYNnZrdxiVE9mFKQeezaGZBUL+ugUJdwbriKujjQIcONq1Nahja0mXKaBxXUZfepXuiMCdLw9YxKfK3/uylxUdF+x9HXskundHRqXWWFS4a8b9JS+CrYsbsK4GiDaavfO28Ve3uqW8fd0rwfNxdglgjT9Mn4Et2m/Y2C4zYaJdN2o3DbIi/VoDTGQeeF05+ecANybb05dL2dxNM8wlwd3r0lUTDqnkm4Fb3A0796tnaOSaKF5iS1Curmsbs72aKmKbndEfrzJjLMDxUdsnkxnGN9Jt5FqfVF7dMgKmKnfOne0b8OsrmyhMg1w5Z0GFA2bwUbPXpgmEvff3W0qWzaBek/eBDJwezSfWxpbgzamHX68g0B25d/3esY74pRm4lYpez6tCZbuy9NvNVRcN4zykrhYJsyY+5mxJ4c9ihFQ86IBOfCf4/ovFujGWb3dwjNMczyf5qCBjO2pZfYDPlmuSGweqp+SasPq6SSdRUWOdBqWzyBRlM/8E1s3OSndpRNGZOMYJSaVCLEuFWkjVN/FSSH380J4lfZRdEN
  template:
    metadata:
      creationTimestamp: null
      name: garage-auth
      namespace: cloud
