apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  namespace: networking
spec:
  encryptedData:
    token: AgCMIqkcyCuvsWL3zmyZV3PBmWm1Eg4ru5wgeeIaTe6PdmGc37NmBddY6WRoV1l5sCLOtil9ClWiSqnAsSe1mVJ76Kgm5PSqu8wnF55Ig/OH+jWiZIB+nz1JAh9vMunFh5sbudWDlWFuyGQqSC5w00MCWWUACcSzOGbmG7HgP86xJuO1QvVU8Ns1qV5czA1glcOvJKPWSY61yrafjftCWT/dFeRYngQbuSZAF4Sp/jRGFB0WltwiOepQjrUgn/JXEQRLR7zoaTODk4HnOlvMjcvlzxUQGiuAIosU+an9IeqM41O3hRAhdC4qF5EZ0gbcb1e3silZNn1iFh6lGHJ1DHu6TNDkFiGYykwpk9NYH0fYorNSmQCffJo9b6u9dHH9oRkCC0t4dPSEZBQx6z199RPAUquOOhM+Z4MCvaFOjTd0kxgKlomMb26l57XIJAJtgE7vhzdffPO/4SffA57ui+qyKC0hZBLURbzUWnQck4BKZYZUY6WMjTIe77fb66O5dugvU+uJGvFKyoOKg3dfYYLyndN7N7rt6PiEDtax7ANxAjOqV27H9ZjyMU/VQG5uKlDV9wHPebJJwsBfFchStH18w8oPZQTC3tISxtezEvZmmtaY8M0mWlb52aNJYr7ox9qEuXNQ3rO2bhRSgksh9WA+Ko4kIGqbg2j8UMLlAJVsaVkC3jEXc9nCTfJbPyF4E3DOXmrY/XxPORFX0TuotOTkq5V/jXIHjceNiW0EYd7Wz1cdgncYO0q3RkJRQ9HLH1BjennREd733dbfLw5sDkuAMkVzABvHih3AwGQ8jhvTIZyzia32RwN7IltJ0Mj5qFYAWjzSxC5mTEQCNs5I1W/fC0cK238jNi+l4kXsWiykU+WZQhExwiM9YgNKlldVFfgZUnsT3kfX5c1PhuF36yhnWvms1R1Sv34uTcsKMFk8YFhdBNmESRh0
  template:
    metadata:
      name: cloudflare-tunnel
      namespace: networking
