apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgAUDiFBEbIq3qsW6BWcTAoqhWT68P6kSQVKY3E3XWtGLfgQa6H1dCsw84dWcLfRcRLFfFft8D4Xg91IYEbPaq6RD7j94CmMQ4rCaqHn6277NYqBDaAQ1FVCnWhdtlEvIRSPCHeAleuDOSsqkhHVhhpmhhBRhJlLATMtSayjCazTnXsQ9KHG1L/IDWJ9SY+e3RwdpTuGXhiTSsZ3r7J1dMBCfigVSfJaL4S9fKU2Yq7gxy1AV5oBkJVvxmo9jl84pVPg6W0DwpOCz6bjXkWnjq7awCss1XAxp+boWlqTlrLP/BAhkx/8NVymkeou9NFzPZLZGQgpnK5kIa11JbP6aYlbpIAnu2cK/9c4lV6cCtOjR1UQIoC+cINNpDMzvfj6fIkJ421iXT1iN4m8YJwvgvEK5voXViZTSCZ9NLgCQbfE/a1yknAmi8vgqjgQG/xi9xhhvK30K5hlrBy1hwjxXZ80jv01XqVU/fX2i0ajBbOL6CYYAmclIq4hQ5dprKehyedGFDohiGaNXiUb89O5LA16mGPFFDoj4pouGURDjw8VXRsnKX0dnjKNj6HQgKTAgJZL4mYYcjGGUYMABk7c21r5jb5kev8SiVhFKWg7VPsjXt7BWPmFRt+u/sUx2hSCzkEbIwQbBjf4e1YGFeo+uq7j6DQvjAzIhcl+q4Lbikb1rl5E1C/F1joqRT5hnGCdHZ/D02dJ6Gc55el7kMSp4xKxJNTZ++AwcZQYKMK0SscLV0csBXmDFD+2yf36DfJZTkXuZenc9Fm89zili6fCmRRAGKcUaPcXqqiQwmL3zC6Gra761QN+rZJN/HmH2ppRZzkU57x6x2ZGoSPVZFomuKJJqFFsePoaaAYHtpytPgnIDiluyk3Ay+46D3RePnhcSNDwLIhS/Z95J6zL3rmX8GIG/Mymc6YjiJVmj1wXTlasyKxQesxVmgeSPbtGDeJINOk=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: argocd
    type: kubernetes.io/dockerconfigjson