---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: image-updater-git-creds
  namespace: argocd
spec:
  encryptedData:
    password: AgBVSdCc9FkSlk8RNWLtZl6LywlEA1UUwBhagvmBOhQpMw3UxZNmdxh9EzS29g5VTAXqqfndGOHlnmSoK8/ij6201mInnQKgrViG3MmLfolFCMNEebqyrnCdHm9xeJ0mlmVK9FiyYHxoSITKMuNFm79TXePlSo61a//pG8rGc9eZspfAsrK/XOChYqyez3cWi2SKeXPpfRHEh4yf+pQ+4ph+K8/h7mCCc3V/FIq6qGBOK2tYfxaGzBrOr9RZF/KjO7qkBZuRgTdOqEj1VfGFEyCmynDE8j1tsk1OMMXD9jDCEtr54p8j6Z6e56VfdfAlswIGw+Te2SwAXpNUmjwppP06vLOxaL1ZKvTtYyI+hUR0gXcec/gQajNhjqFTp37nzxU3NttcbWksUEPUabQnaZHXnywLi3YQk+lCP8Cj1ssWu7SmQDOHXnnfR4LCNuOKZfc7ZQPXtrmWwHn0sPnQKju2n6TneCAAT8yfMTlyjKBSd2kCpVrBrUDpAi03neAbFkUGq1M2K9OmayVkPqQtsB92lwxHB0QMNmdN5RuR2Ymn+IYN9p+MS+UUuGHKWDiyGjc+aG2KqC6EVVSizouBBcZLBo0l2jW1NWiWMTnScXuudB6dzZI/Ty8ykH9YAbU+M7qHRoUsVbygzXMcCfzK1/Wug1hpQ2bG9AxxlUMjX0iAWq1YGpb1cidtboMdBaGBf0e9ng3d84eHMgaliuAVOemOHiZEzYg++eLkrZkA3Gfgz93V8PEahAi5
    username: AgCFQEB48r4I2bFU8VOhEuYUHcpU4d1arAQYkAKCiT38gRC5Jb4Iw3EHdnBHRmKw4ARyWAsuBGJCpH35RsCoxFokP+lWBy10x59po6/lsMni0wqpKH4zK2/YqCtCV45fxhqTM4wz3fMerSmnJeNepcTTayqSap/F5EnxYVyz3n5uzcGB/TTdVJhK+Ft7vsBNYiGQ0dMfFQnK9ElYNqpgKXX5O2PAPz6ix7pIz6CHs6wDP74OtZn85eoJos9ZowtO7sg4d/pnb7F1gJVsse5wC9URDMN7xnE6k/fJWU/7wWTQn1l5r/kdC4xpeKm5Tw/eAS18PbremeLCf7ybPKN8cnwuSzC8s5pBU2rW90saa6ATj+QQdqj+OuYbPNkKCbAC0g2ojDKWNe7CllNLR8P5KIOxz0AI6irC3k7zJxP+7wWb/Uf2yF3jC6+xdlhY861OLuZA0PcHt3dml2uLBhsQdRR+xMsCjv/Ovuhu6BOSEgJ01B8XSnaJLtOmk84N+w2MBfX/CQAHxmHrFFsYztJV/Q/TjoFoNTEY85iiD8jzyGaUL6+gGGGtrPLpfMmN6OAgBAOe3oKxx39jFN3p4THmN5BqvaDk0fs6HsUh581tvbXKzjrGLkyDazjSsA+yB5dRX2qDsdKDxBHeGRhn9suAmi5uxKKgH3kPYHP2W11SfojTh1L7YpaZkt//6YmlaaRHi9v+VvjMsEknCrC5n3H3iGE=
  template:
    metadata:
      name: image-updater-git-creds
      namespace: argocd
