---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: image-updater-git-creds
  namespace: argocd
spec:
  encryptedData:
    password: AgAemi6j8fb8Gyq3VEmL2tTitvAbzNs9Dr0NBE/x2Mocn2z6poigOqh9+Rb8PL5FkQnY7DVjQoTZJMcinh9Uik7y5sRfVXNQPuT0vHg4SA7E+e7QCoJXo0XN5DeAF2RzeXU2HrBDDNiertoeOcxECFlbsWHcCr0Qbh7W73fsZj0UJkr2I+jTmf4rFYNM79Oo1GV6enKS1Qoe8z1VYsbQDrZa9iGfvIb9SmTGjOqv0QQP7Ka+8Pz4U652jKa1KzP+DUCy4HiL6HCSMaczvWkKoJsACjKcf7+Fhaql5zpY84TpRB2viUJt3bBInvAUSJwQqAqMSpexeH/odDoKRIv3ZWme7nGlNgps2bHfZc9u/BVHGVbgt0P00zjvB20EWcUL4y2T5mYYtiTniNj0zanVbaR8+S9IO2AlCZ+65ewnEbwiumse+QLU2RRbOrQMr0FD8KIS7VYYC5/RgdNt3Q+3fFN8Og32UzmwC2B+aHOuxAI5p9Xn/mGmjmUTfMNFRkJnS1Yxna9BvHCpcEqCNTtxMdhjpvwenuT8fhLojpFwSdpZWPoBIIxkDhxgr6v1XsvpI3F8+fS03EHaf8frAfRa32xEQjOkqp69oiQLU/MH0EU+SQYdqN+D9mfd3JWzrjK7Vymwustw7WiQ6i5fV27wNXeG+e8ZMCKJLdf3X/mlEwgtlbYsLTSJhBU/9R+f5yAXQULu6/6zYCMx7OH+tTZo8N8h6U/rDSk1DM78omNlF6jj3mBapSYdlqZ0
    username: AgATI1bKbCPGizF344J4joeq7yy88sSkn+JXByI5Md9TXDdSrN0BhP2zm1OFa8Z+ttnHEKYLX2v7lFH/iIzf+XK3Ci7M4cogPcrHwA8avQwNrDVM9vv96lqlaZ2Yb7fLqOR1RL0PQz/xkIav/aq3ZdMDP94Tmo8rKklhbL2NU5VJDiN95YmZrYQKgdqVp71l2LmWNV1C+8xR3RTGGICgbLPxAFXAcQMAUP+gVyQojA0WF3Hwf+PXXvXjG1lYjrqAp+AnZzIbpdIUeP6FwHvfHZEizAzg7vq3l7UT9hQy4BDcvXzT+iOOSua0qpQPVnW2Y5h+31nkvZq20c5LKQujEcd9Xj+OzUFidIHL0ke+UIvb+SAE1OU1aG8C7eNziwS+wuok2GHd4XWkPfup82OXtCcwZfGrnL9noxeZDP11fDD+LBhfIzqHdEp2AtqKlVg+BwK3BfEVlMkjVA3WWpDpOChOqkves0Jqz8actcTIkIbuVGTBBY5jErUGqu1VCK8dHmhjXJrajU+eNFuDj+mlNPGHuyQ5e4x461DVFRE3nb62G1DAK1Whg7J5XL72mlCQRlRESiqfJWxWbg6dHDY7e+PkLLrS1dwOtnKnRIxcz/Itt6Ta6MUOaktUiDxkCwlu+ZIhhdIxm2wcnZ3AsGmBM+MdpUSpUOLUIys+svZ6jFckFPVM8EfNJ/RDN8nD0lF0ySzbTlnjpGbe1mfgKi14S2Y=
  template:
    metadata:
      name: image-updater-git-creds
      namespace: argocd
