apiVersion: v1
kind: PersistentVolume
metadata:
  name: tank-movies
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: media
    name: tank-movies
  nfs:
    server: 192.168.0.254
    path: /tank/media/movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tank-movies
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: tank-movies
  resources:
    requests:
      storage: 4Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tank-tv
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: media
    name: tank-tv
  nfs:
    server: 192.168.0.254
    path: /tank/media/tv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tank-tv
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: tank-tv
  resources:
    requests:
      storage: 4Ti
