apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-qbittorrent
  namespace: media
  annotations:
    recurring-job-group.longhorn.io/default: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-radarr
  namespace: media
  annotations:
    recurring-job-group.longhorn.io/default: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-sonarr
  namespace: media
  annotations:
    recurring-job-group.longhorn.io/default: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-prowlarr
  namespace: media
  annotations:
    recurring-job-group.longhorn.io/default: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-sabnzbd
  namespace: media
  annotations:
    recurring-job-group.longhorn.io/default: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-overseerr
  namespace: media
  annotations:
    recurring-job-group.longhorn.io/default: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-plex
  namespace: media
  annotations:
    recurring-job-group.longhorn.io/default: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
