---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gluetun-nordvpn
  namespace: media
spec:
  encryptedData:
    OPENVPN_PASSWORD: AgB6BNfCH096LvQme6XKEpEy9Uqyp7MUsCc/Ythn2JvXmWIlGmDo215UFzu2/9z2kyG4ln4lSFwPHCWL1+6Kjw4B8UCpH/FBbG85PxRjimoh0qgEU0a7juRMRv4wEF3dw/XcIrqqfJtjAQpP6C6fr8Y5KhNc9UfwFgaObrWNhsSYo+v6MTAdTuPGLV1nJpu3BoTqgbX2McHYrk5a3vOSXingFcWofS7BwWmhewl52WGXCJAypRe3T16WCojnf36enhbWGoDHPe16d0fzaWYkVyvuaydQiW8uTqM8I5kqomp8xY8I61oNZClO74jYaq/W/ei+TIEMcEBy4v5RRLU4vs+l/yJJypS6MP5zI6JY+DEt0S9yJF+XaxSE+pJULEdWnYqv7vp+bZ/jbtJtj2JrqSVcRG57WJKc7HqVNGVmn2vzPD6qhDIPEyTaf86MnTLmt2r+5VIeL9E6NYvfJOxwKHQ127NjfXdlDhdiY/ZEnQMrPRNgGGACQEbRTaSuZ8rmzVefG/Z+V3Ra+EFEP5k+pwVSYX+awn5WnDIpgU4iQ/EA13/CaS96uyLl9dVdwev/CvC28Wx1svcH9rf+5JWSQcZjJGtudGl6YYsPJdyFkPYhEU14pwgGn5MSjtH87oh79xM1QP4b6q58DKUohaeGJnw+fl9j7xTtL1VWxSs5tqD6l6asuFfi+5rf2xAMAgQlB/f2RXkavgthKXjBt+LlSucOOvm4i+Po0Zs=
    OPENVPN_USER: AgAd9MxLEu5MKDKHleXFPlW9LBIuZ19SRQkuusBZ3eQ6Ncwso6rgAbFgjp7Qwdf+ibetaM1U6Tk/4yzq6swqdyobCoz9c2qdbDBd68ZQnQlxlv/pK+abYqNrZJ+2cExYushk5Kx2uzLLHNnnV9vIGO6AqHWB0L1Eb4GU6E2Cl4HciopbECc/Q3/cyFSHMuyvzDT5BOuZ+zCLS7rcXji6djudDjXj+iQdqZM8gEEshMlpcpYnbZoczivsj2rkG0nybI4oQXAiymA0hiutWkDiySqots/ZX/6jv5xYumZNfkia3CzObsQM0w+EPLGYZGUG4Kt+iiG86fGYVKTOKIUxwFh4R5sNc373g/AGL8zF6OYWd4t2PFbN1Ui9bcdj/vpjjVnSIZ+Y5EWpWHnuZ80VdOWSmwvJ5Ndg9wVYgr9sTCYB0VsQ/o0k+Q4ey3AhIHI1ZjqcugxPbamnlEUjMCKSmGLcNOqRHXHQJXbaDQ3jyIPTxftgIMlDEM3u+3SUYln4NPxTgtcitOzIa6Njry7wnXZAyIJMNbOksMvTLZjk8OnjMjRobksXyYPQYnp9WW0zey5c21hXFJQiCTaatu5/Rhgm39xModb3L/oTnPWblXNejcyAkCZKspc3IzC+EHdOMlIIJHqTRVS2DvRE9i+2rQFBAGxTiU8PQWjA+8opZJvlv3KpHzP5N5XslyNTYfF0obVnC+aH+j9O+MazCFhlnoDQJTjm68dqsOc=
  template:
    metadata:
      creationTimestamp: null
      name: gluetun-nordvpn
      namespace: media
