---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: qbittorrent-auth
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  namespace: media
spec:
  encryptedData:
    WEBUI_PASSWORD: AgB5fUF00bm1ZORtslFgi7V0fm2rjKjyhVZ4USJzNd8OFGxrV7Su7f2jUrVHULIKXM7U1GbJrDK41t3gWaSDMzOx63k00cT96u/0/JXsV88ZgHqGKdBct8WW9b41BvRR1SULK4QYRbZZJozK5n79EPcPMS4Wz0ypVmntH0VpS8LzSYzlmzNRQIcEmbvqZNU5RsxhBJ0j5af2ddS0VSm45Vm3+7cPNC50+5EoeaD5GHG/49foc4KnhGNkNzdLk1JkUv5Kk9z6buq3aUFpodjQ8eK5JXx/88xn2KrwlI0yZkaU636i8FkDXYiv/KajXCQBiEdfh31mTUHGQtIywFhogzhyvAs0oUhxT3r0mcz5QiGzgwX3YFS/AHh7mMttj1SoOOh/NkqSzNf39959qnYLP3rJBLA2gTQuyOrr0EuOJWQ7K9/sHqHsyWGX6rFgzekHC8qBT4kNdG4EOU2FKSE6Z9EclX3+Kp1yTSgtNvaqdfVLVWtXTGS58rh+eICFIFcx07ga4cjVMg9LCvW7JhDdOTaDDbAht6wHMmzS09lZOiA5ymdSoBN34shwPVTfBqPZ7kerleJJZdLp3CzbQxtXk1rZAfthYJEPT9oRdhJRuf8cV6YKrYLM8CI0H3+U9zw4UNXNn6As7vJMIH/5vr3eEUK8UNkXL//FTE9ujQKUoNMBAULz+qgbyXPh66yEv7hwX5hndNZy7bVc0xtEaZ0=
  template:
    metadata:
      creationTimestamp: null
      name: qbittorrent-auth
      namespace: media
