---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-auth
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  namespace: media
spec:
  encryptedData:
    PLEX_TOKEN: AgAfhdDbOw8A30upL9Zf08TUCbwhIHO5j1LfaAFNABDsr6EXOV1e5u7oxPFkZR2MHfPbBWNQWxwRIbw1Q5DjOcCbuGTC6GooPGycFqgSvThlraVIFMKs+5/wxsHbqK9Y+Fil1IfZ2/Nw3zVWEVC/33qNFNKK/toRJdp2WcKvG491FKtk7zb77zeEoMd2BLeYi5XYknggeKI/vqmQAkk2kNLT/u1s3tBLDnpDDjZelps+mIO9THZCnVD63LqNbg3IOFKjr+iKUO48QDBVHki5a7002OlwzVTG8L2Tigbx7lIT6o3Tj1h8+x1hBBl+la52NfZqSaaGlzti0ePiiI/ncNvALzqoSrigZzhFT8QaLUPs9ca2drQbh/lroztgmP1ta9uigWgkbON0G1pyRPxguurpZUh91YmhxobWw9EpAX5QkHrrNql1zr5cNmr1dzMjoMgn1+RFjOyvgEulrSKr1OD4hpa2ZLMJRaURpLEHiIzMPAAAf/ldIAEj1cxdB8G5qYAT1HxHGSJxOn98KGKISJudqTZBMxOifhbVJY5qGZT+/94bzdjxs6ovy9nhV6kwxgXaBbcxzV5KKV20duB5cpWrau+/d6BVePANS+k9tUqmHp0BB6Etf3u0aLSJTxkZ80lbcGzd5Ps2oYDhUBFXNNjS3RsNuJjRD98rR14is5T2yg3vNpqOUzuw2CjlekrdKOG06Ah0uQ5dcuPnp3NjtTlxcCxy4g==
  template:
    metadata:
      creationTimestamp: null
      name: plex-auth
      namespace: media
