---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: qbittorrent-auth
  namespace: media
spec:
  encryptedData:
    WEBUI_PASSWORD: AgBTYadyJnuBVPwSYam4afUatUP4LI34C6zwfdbFCA0pI6f6QIXtbscyQTHtuMiv5uHpAvyv5fbkYOsxSJ9MKwsx/IXJDBEunq3nZVl10LpZtrPBgPyoe2uQz0Nelv8Hxirmibw9Msur9iY6XSaqsD0cKyw1363XYHsu35UKp0f2EhVehDri5aXkzfvqblb+IFhr5nkJJlwerl6/TmI8ed9HZid3xjbpjaWw7PaY4vBIO7zdmITWs53TtBn6Ut4/5SvhpXlwIc6zNXsLuH4fwLfEIdhIKxanqBfKCVSZIeCWoNqpvpaXihxQ386f0rrm+pHYMg+iqvBhipugoDtKhzwAmL3B/uddRtXMQVIQPkQGuDMlu5EAXcE98eCEeWkJb6qiwUwasBt7onpxoCL3CT9xThINb/Oy8uMLsSe7zdkXRjZQJbXKuAThg/AunwEWGINcySbR0Vwh77ZIlH2wXdokcz0g0xWW4kcPy0o64IaaNBZkw+noRSh82Cm1DA7cWn+db4HLHX0YRfhIkDAEdLMHbiDd80zdLVXrfBOwZUHXvJ0VHy/88/RZDIvvvOOJtGoUVCYECSS+2Lm7zHSTXAKLy6Dz+T/XahPIzHUUa89o8oyBfAIQ/ivdd/uqYicWIAhNQjQfbzoNW0pQTO0grKdi7DRqezfhT60snEygU4tF7+6TO9fhRreJamcb1Fn8ytuY6FigBTpYZZZKuekQ
  template:
    metadata:
      creationTimestamp: null
      name: qbittorrent-auth
      namespace: media
