---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: qbittorrent-auth
  namespace: media
spec:
  encryptedData:
    WEBUI_PASSWORD: AgAt6jBHTEj55dzg0N9prer+ikapjbXM/9dP8pTsoHfVuT2bEJgiRKrtnDf3JL4fJL+fZvv0ACue4TBqJ1OvyLXCJbH7GWJT+r9SkkgdOhPvE3eX/wn148KMXJ5EQ1Tc7wT6I2e7/UvaiZe5YpUyjXZNcPq5w8xVAOMC+NcFkbOW26JGH09OFynMHB/JT7fZTCne4BBf4CKc6gIBdtmPL0d5HeLlehsFrmOI8eah9Eu3h/WDnzCCtInAQlCf7fyFFrvzt3SPDsUFfmS7wPWRmvxaQZBZqxL2EI5GBN8ScC3ATSqBMxBjP8I64UB6Jb2ijvfuZkUctRuZU5kAarh80GYfeZZZkxhRroFA4NhFbe/90I94kiTxtf4VF7RUMpqPAcpZ3Osrg7DqaVqfaiiWEV8IoeMWWl7TvAes/hXciybVlRLCyHJeoJLfAMWHsWsBU9pM0laPSsVAJQbxyihVjHE+xEtOw/SJeAZRbw5vBJJ0k5Cmi++Pugshk1ZvUa92sYjshCCgcMWmLgZ8HkWpV0BRPy9+LotU8ufQq3WQ9nd02hHpYlp+AtWPMBjW0Z3LCgGvh6xRCOgVQIUOmzbG4+KmSPlo8rGSxVJSi6D0uB+FNLrnstRBU6OpEY7DAc/KJcaFlC7Ye+5JnAqH9pUU6HAGPyS7MHq8Ww7tGApkjaVub6+DNdtmErVku1699xNVwiqbBZE2sOfWPVAsn8JK
  template:
    metadata:
      creationTimestamp: null
      name: qbittorrent-auth
      namespace: media
