#!/usr/bin/env bash
# Create and seal the GHCR image-pull secret for the games namespace.
#
# Most images in this cluster are public on GHCR and pull anonymously, which is why nothing
# else here carries an imagePullSecret. The DREAD server image is the exception: it bundles
# redistributed CurseForge mod jars, so its package stays private and the cluster needs
# credentials for it.
#
# Run this once, then commit the file it writes:
#
#   1. Create a CLASSIC personal access token with the single scope `read:packages`:
#        https://github.com/settings/tokens/new?scopes=read:packages&description=homelab-ghcr-pull
#      Fine-grained tokens do not currently grant GHCR package reads — it must be classic.
#   2. ./scripts/seal-ghcr-pull-secret.sh
#      It prompts for the token with echo off, so the value stays out of your shell history
#      and out of the process list.
#
# The token is encrypted to this cluster's sealed-secrets public key before it touches disk.
# Only the in-cluster controller can decrypt it, so the output is safe to commit.
set -euo pipefail

NS=games
SECRET=ghcr-pull
USER=isaacwallace123
OUT="$(dirname "$0")/../platform/components/minecraft-dread/resources/ghcr-pull-secret.yaml"

command -v kubeseal >/dev/null || { echo "error: kubeseal not on PATH" >&2; exit 1; }

# Fetch the controller's public cert from its key Secret rather than via `kubeseal --fetch-cert`.
# The fetch path goes through the API server's service proxy, and the `deny-pod-ingress`
# NetworkPolicy on the secrets namespace drops it — the failure looks like an unhelpful
# "502 Bad Gateway while dialing". Reading the cert directly sidesteps that entirely.
cert=$(mktemp)
trap 'rm -f "$cert"' EXIT

key=$(kubectl get secrets -n secrets -l sealedsecrets.bitnami.com/sealed-secrets-key \
        --sort-by=.metadata.creationTimestamp -o name | tail -1)
[[ -n "$key" ]] || { echo "error: no sealed-secrets key found in namespace secrets" >&2; exit 1; }
kubectl get "$key" -n secrets -o jsonpath='{.data.tls\.crt}' | base64 -d > "$cert"

read -rsp "GitHub PAT (classic, read:packages scope): " token
echo

[[ -n "$token" ]] || { echo "error: empty token" >&2; exit 1; }

kubectl create secret docker-registry "$SECRET" \
  --namespace "$NS" \
  --docker-server=ghcr.io \
  --docker-username="$USER" \
  --docker-password="$token" \
  --dry-run=client -o yaml \
| kubeseal --cert "$cert" --format yaml \
| python -c "
import sys, io, yaml
# Force UTF-8 out. Python on Windows writes stdout in the ANSI codepage by default, so a
# redirect here silently produced a cp1252 file that YAML parsers reject on the first
# non-ASCII byte. The header below is ASCII-only for the same reason - belt and braces.
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', newline='\n')
d = yaml.safe_load(sys.stdin)
# kubectl stamps a null creationTimestamp into both the object and its template; it is noise
# in a committed file and Argo shows it as a permanent diff.
d['metadata'].pop('creationTimestamp', None)
d['spec']['template']['metadata'].pop('creationTimestamp', None)
d['metadata'].setdefault('annotations', {})['argocd.argoproj.io/sync-wave'] = '-1'
header = '''# GHCR pull credentials for the private dread-server image.
#
# Generated by scripts/seal-ghcr-pull-secret.sh - do not hand-edit. To rotate, revoke the PAT
# on GitHub, mint a new one, and re-run that script.
#
# Encrypted to this cluster's sealed-secrets key: only the in-cluster controller can decrypt
# it, which is what makes committing this safe.
'''
sys.stdout.write(header + yaml.safe_dump(d, sort_keys=False, default_flow_style=False))
" > "$OUT"

echo "wrote $OUT"
echo "commit it, then Argo will create the secret in the $NS namespace."
