---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minecraft-rcon
  namespace: games
spec:
  encryptedData:
    password: AgAp/QA3up/nArmy0NhK5irbvhB4QX0DbqPPIU4pg1Gb/mCCa4rMeEarUPid4NsSFeQud5CjsfPqx0nE6iZL7X9vGVvU8jCqWBp2MoMtInccxleP9FWWxulgaFqOTUF5YpaiL82pyIA2WC3EMGXmGDlNnU+vbmEAuoUydeFxITVc4JtoE1ilK9dNHQyycJbBg5gHte2scVSTXvY1M2iXvlxh4KKfsVA7bNhkSodXNxNBTRk8yjM5jwt7IaFQQoaCtdvNxrXn4Hz/HqyAR5TKCl21La/TfLRcRuEO5jDy7xIehu/+1GWCjQvGzwrpEbJa1uS95GiOOCrUKDX7f29LfVEgiLTcDeHhrn7TKoecx6nQexINin3lZ/P4w4czigb0n6rXuAlhGANj8SQqj9fUiTycxdequaMxllWcQpj0Er/peEA9836x/gz5/P4ECIiMQ9utPMDvnjxFrgk3Ye82FTJ28auN1Q5LhFXFxY3N9edTeUaG+7IqpikID5McYVpHX90mcVaOJ1u5FBLPPcWhL2salMyIHANNoYgnRH0jeyhZ17s2qoh8Jk7vFQ767dbXJzeKya8EGdKz4pOrnI0b2VDDdGNgTe5ZC08lAYXL+wairEDREdP4yWq7grAzWs7NFaQYJn1zMG3xsdGnr3KqgAZZNxvu5vpPMxbOnu8brauZq0dQfcyouOsmS2lFPmCRkUdUzZZKQ+CSMoi8QPKKvqY0GoPqkDrU8U3hYHYvuFqS8A==
  template:
    metadata:
      creationTimestamp: null
      name: minecraft-rcon
      namespace: games
