---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: valhelsia-packs-s3
  namespace: games
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBeF4xZktGxQNfTInGSanOGB3VJZlBbE+sN4Nc8kL04erPMtWLltNYDHen3UmU3lt8wGoaBOTzTo7YVHNb+kqPFDuJuYIhwTnmMsGhJELDf4IoPlJ2sOPrldJo9S5qX1D2CBuzLKKsnTXMhZ9j/qQNKb9XLtM3c+3/ng7+LGngKAjzO0Bdr+P/DUOp04JRqxEw/AH62/p07BlQB5PcMoYfk7LIN2I2u/KjVlLjQ1iQgr3d6AY9egPR9mBkPVMXoTVYkizSOb1xEkj2w6CMkFYXSvK4i4uZe9KoeGVk1qWWaFWPtbR+huREAR949161x3d+gMejEYk9EqQzKYWyZcGYGfeXDDDjuAPJ2urfy/8JF7Qz0pvLsZtnrcWBzWTJfxQBfkp8soPJhV1iCFqYLP9CoR8o8qq4gQ4jis8sM2qoGQp3+n6kObDv2K5w4dwfNghNr33bxCoG4XMS5kOAEaNS0OHSjzXC3rti280myKL9FneoBcQtqGOqc6XuEGaiN1V3Niy3ZDgiC2CSpPuF0uDKOXr+s+cpc3Rdx+Ximcq0er4NfgKOuyDKJK3KIWnns8+OuDJjQ1s8vkBw1LhX66IZw4WoaCK3qU06PFzQAQYuyCCv0z6y2zSWgSJHkK4lmRn2We4NyoUGahNnq6oDNN1Nbrfsie3xNvR9Qp/Zmjo+/NwK6DSP6bVwtOk2gKrc5/VQ9Fp8k0jQdwSR8zuDrtZGknRa2BFLlJOyoyA==
    AWS_SECRET_ACCESS_KEY: AgAsEyCPf94wcQ7iG6QnCyIEHtXoB3kMxKUb9HrKfH2kSMorDx75kQe6yrNKDR9aI8pmsv8k03H0hqpW++ot+uoQoCh8ekL0FFiv/LjeB5zqHpnsGjfOJmIc75Ui98X+ARei2ni3yl4d99Sc2K6m0DYFYobOUqGmUzuXSkIvSl2wIRXCDPEXQQVieIMpI/IxVebS3UfpwenfkJ9Ryj/26lYgct8LbRRV3HO6yshWuVTPznKaMjVZQCm2hpmoXEygiRD/VTyphX6lvnogA0bfzBGF0FGJpIZ+UEvK3bYsiTL5n8stMh6pp7K6AtzEUVwBj/b9xjsfZ/34lEoUmlvIJeGcZXvtPaX+1AVjkkiCaEl1mH+4Gtw3s4VK48R5uHsOMbrgFXRc7K6Oue3gGGWCtH5r4fHl1NFvsQT0nnmkZ0NCpkm0JYgoNN+gNxkRnL2ZPWLYHm3rOK3ig9kAwlhHdQApi65Oq7/laqQgMFeByzmtV8nHlDwGhdX5ePpbMPgB5aEwH6Lb7f1dYq55E7lXGxZRYb6hjL8jwnCYlkH14MeTzH6kaBilgIMoaskcbDk3PkoTwL5ccG7OLvWAStd//4o/PZEHr6nzMR2tGm5sWLt/AdLuEz+8hPSlQBLXyQVGSU2lGhicRIiEYDRez73tVyKjHKLhMKgKK2U9rYswQhi3zL1SVIQDF7e9cYwm+v5Xf9ksGfIoGsJxazDPdD86PMilGfy5dOx3PayS+FRuHzEEDMnc+KXPJM5SPcMu5+N2cdJytmEuMAYkFuBryWyyhzCA
  template:
    metadata:
      creationTimestamp: null
      name: valhelsia-packs-s3
      namespace: games
