apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: images-secrets
  namespace: images
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgCtCYjkCnjYr3krOgGLW4osMC8kiSAhlxUcVb5H586X80/KAG9WUU0WVhUNSp6npH06cDU8A3fRq10jeYwpi9gbQsZ8mFh9yTe/JQtfUk0sGLmwfpfsNl7q1WtJtykMlauyHz9edYVs5kWtMZDWtUfNRXRK0F3gtFMFhMAeKdX5iDiez7ZsFpR4+ySU4sFU6LpkWV/TOIUXIH/su5ZCMbwpRloDYxBlVaWbnAYXqg3bYzmaS0xygjkJdQToKfhNwkYmWYyDZS0aZUzTiRHzwlYV0Q1Z16a9ETik2P2/M+l4yvvQJTAHWtSYAlj2jf9kWEwMPpaoxkM3fKXmiqvB44OF7CXlPtabORrdKBnqxRQmvABcjtc82XTAYBhqpFZJlk1IAFVWR5ptKr3NMpFbAkkZZIoQpTbzITl277FyyL7p7i2yWuA8nwBVDDJVBPC4CyOi+eHEdbzdcVTV8gVKqucwH4ZHyZRzU6iRpkKApuWT2Ma0o+msBrxkzbAdgHDQDSI0gFxcUjNOKEAWOqFqKLMO0/P9Mnz8cRXb68VT2I5pDU4K2TuJHdrxKwA9ix5Am1hdF/U4WiTCHQwiB0ihIBjdomfmHx0eEd49DtKMh30ClF/0dFTewdkf61+8zApZbSfNV8obEmlDpMN3LCXUlkWc3pJAD9TcBAKe209VAmZgoU3m3pbHv2MOToWCEljHLmEtGk4im5tYVcxCagT9
    MINIO_ROOT_USER: AgCAy+XdKMyl0M4iFgCanAh7TE6OhIgQ7B6T8mDfDyj+wJlLZp1hxHa0IyYkPNWBcCoyNgzUYxov9ICLwI79tCmdWYAVrV1qHyR3jAxxIZEy2tfMXIO6sya9wLG+PnFp4IDBgrJftnfyVV36I1x8NzY39kGIMTNuFTmeS6BVHeWrGIWZDpXYMZcCUjQydKodTB6AGUroIYNmrG9R3OhGRzDLp5vAyoRBXLkPGCPpFYxX7ivv1+Fp1ArtKZsCPmrf2zM483MvXam3fUDtqzzrtO9aOwMGOEMPBwAXb/EkuyI6O4HXmLLi/oGyUyMXlOLMV9Ema3RB9Gmi/K2+f7s+QRNZalm6NKEJhOaRX6yFb3Qpi+FmkGB41EcM3EiAg+li7BZsq8CzNllkdISfpLz7KyfWGQnMFJ22k5ydpzmYESq4zEDIWxYecZiJ2OrNqRbUGwWkqPOh70rYVacGpe8uZzXqJMGTE6wz2XtGLUPqbxdeLV5TkWWGrP+sMlrVFTt3pS3IwQci65K8epy9XEOLYjRkaQpmz3etoAite90AF4Z0nbsGyN9+U8r8gu4EFMvbE+bWssF92GsHVIcT6Ywnz9NAubeJkDpfAjIq/0pNiFOuyYVWPKdL+gekLcm5MT+5NJh0hIP3As1arA2XpHUg7GjldsQjomgk4UWsNm6okCJ8i2UDOhA7iSxVLNplhefJRjvuK/qVZX6Lj/Eo
  template:
    metadata:
      creationTimestamp: null
      name: images-secrets
      namespace: images
