apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAMi7Jazc+NKaHMHKMMFZYDBucisn1YhYr3hwMqVfv1eeQdVPWLZ48SIX1j+IYl8UulKSOxMuRRjkoNseEb8BY3nghY6s+CGP/zeOnw1XStjjO3HKo6WioQFIMOhenZMWtvIX4lOtjgzDg7nhp2qBs47lHYe2cSTLe+XSSjKYW8ZwH9poHPAPrld5sApXDdqiUZHsUfjLGcfsAM9ZpGLcVONLJ2Tvt0jZsgF6Zys4Qz/2MjZU/eH3eCJevt7KdbI4KFr6H2kddgt3wlKDz6U6ieB2bnBG0LTeQne4r991TH178SrDf9dutALmFp8rnSaV2weOtAhoNMHrVCmIOx9/HBBTaRi/Z5gDlk4WCAhbXSpe2nfptgz26BxjlMXneIRpQzm3eOpNlnCS5WhEoGpdkLR/r1xEOKAKG4nuwbjyqji8CipltyCRrUpjJn8oyOfrCF3fLUOCcQfSQfrCuR0eLJBg+abw7ICpkJHHBt37TQadLW0Wac2Y/9RspWDNISd/K9kkLwj9ZFAbD8nRaPog9y8fSU3zDyc7d9eDpPwXKylQ76a21h0gCGsrDwMLF9ZeQihjj5jEbxT5gjD/o2yTfwGXOQrwhpoRsodcrUBo2Dlis2CiAFk4F67QzlINvt/uI4kYNCd2d8NgYu22vbFu7FhKsH5ROdHoLgYIk7eM7Hw9UipUOul1zOdqkYZeQaDQ0xzm3lr/W+FBy6+MbA
  template:
    metadata:
      name: grafana-secrets
      namespace: monitoring
