apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
    chart: infisical-standalone
    targetRevision: 1.5.0
    helm:
      values: |
        postgresql:
          enabled: true
          image:
            repository: docker.io/bitnami/postgresql
            tag: 16

        redis:
          enabled: true
          image:
            repository: docker.io/bitnami/redis
            tag: 7.2

        ingress:
          enabled: false

        secrets:
          existingSecretName: infisical-secrets

        autoBootstrap:
          enabled: true
          organization: "Homelab"
          secretTemplate: '{"data":{"token":"{{.Identity.Credentials.Token}}"}}'
          secretDestination:
            name: "infisical-bootstrap-secret"
            namespace: "secrets"
          credentialSecret:
            name: "infisical-bootstrap-credentials"
  destination:
    server: https://kubernetes.default.svc
    namespace: secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true