apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: authentik
  namespace: secrets
spec:
  tokenSecret:
    name: doppler-token-authentik
    key: serviceToken

  managedSecret:
    name: authentik-secrets
    namespace: identity
    type: Opaque