apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: deluge-vpn
  namespace: secrets
spec:
  tokenSecret:
    name: doppler-token-deluge-vpn
    key: serviceToken
    
  managedSecret:
    name: deluge-vpn-creds
    namespace: media
    type: Opaque