apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: kimai
  namespace: secrets
spec:
  tokenSecret:
    name: doppler-token-kimai
    key: serviceToken
    
  managedSecret:
    name: kimai-secrets
    namespace: collab
    type: Opaque