apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: mattermost
  namespace: secrets
spec:
  tokenSecret:
    name: doppler-token-mattermost
    key: serviceToken
    
  managedSecret:
    name: mattermost-secrets
    namespace: collab
    type: Opaque