name: argocd
namespace: argocd
project: infrastructure
syncWave: "-3"
repoURL: https://argoproj.github.io/argo-helm
chart: argo-cd
targetRevision: "7.9.1"
values: |
  global:
    nodeSelector:
      node-role.kubernetes.io/control-plane: "true"
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
  configs:
    params: {}
  crds:
    install: true
    keep: true
