apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel
  namespace: networking
spec:
  encryptedData:
    token: AgAx+aVXXUlwtMF9vBk/K2u3awuIPPZQGkEGWFM7fY7Y7PP6ePVKuv/HjQFkArdFXasQHGRrBXIf2Neh6azc4CkRjXeh2dYzwB3JgG6KBci+WoEsY/SvPBiq+eyYMvpDT0pUfKtE1dAdTlvLxdhrklXLiccvhCBqAzTC8p7YtAOPTbkh+0kgiXerfPJBQnFWaznU2gTK6VMWntueT5wp+TT238JVLhPZBdDY5KsUW0aGLI8JTRHV29wN7QcvDmaH/l0VWeySSGMWvWIURq2MlqBwb3JYrAUtLXZyWCH3Td1rMIXcD/k0XbNA5At3sKdsMHXO6QC+9SISJMp+jzvDPZ9SH6zL6jTCIrXN36jhpMGz/uAX3RP5rPZRaKbV3gmxagrqWASsL9HYXB8PEZf5R4MN/hdwJYbdfCt1OSpCqW12BaLR2ssMHurojVMGBMqIHusHKASDrm4Gn9mgTNVUELhdoYhahFZYtmKEgqIA4gajM8WdSmXYavJQfcnbFpO7ryDYnCvisrmlmSEXyBPwNryTvzvE+4TsLDRDEsnq7cRpz1/b0o5J8K9LmruydUtUrg+ao4v4+Ll9btRp6WrZPEsKKCNjyqTHogz6xcZD/i3f1FGrzBzjrsvhTg42qQzKSSmaHEUc/zYr03Ba/X3uj5KWQNdYWiN5/pap7mTFbYKHhQGsMJ5oDmMikuAHJwGAGPMpTaZxleDAZA6Q6fbsRrYk3d0k+taLgVy+9Qlk7FS51mx9RUwa2qsmaiKshnVp0euwhUh1GD2k4n5F2IWaOV3rY5vhPkoyzS2XwlCElcSxpH3nrAMxpd3Vxuo6yGMpbP1sbo2fM9zGB9tJvYnE7hI5/S126y47OmPfKUgE1aB5hoAoNTG+mdEMZErVRvNw2ztvxpySkpkUbKTGVgxRYem7e+w2h8z5FyZt6+qxk1KB6Gfw9eNXKzUU
  template:
    metadata:
      name: cloudflare-tunnel
      namespace: networking
